import { currentTimestamp } from '../dialect/sql-functions';
import { OauthConsents } from '../entities/OauthConsents.entity';
import { type AssertRowKeys } from './_shared/rows';
import { TrekRepository } from './_shared/trek-repository';

/**
 * No method in this repository returns a full `oauth_consents` row (unlike
 * `OauthClients`/`OauthTokens` in the same domain) — this interface exists
 * only so `AssertRowKeys` below still pins that every scalar column of the
 * entity is accounted for SOMEWHERE, the same `OauthTokenScalarColumns`
 * shape `OauthTokens.repository.ts` uses (Plan 3b interlude B, task-4-review
 * F4: this repository had no such pin at all — a column added to or removed
 * from `oauth_consents` by a future migration+regeneration would not fail
 * `tsc`).
 */
interface OauthConsentRow {
  id: number;
  client_id: string;
  user_id: number;
  scopes: string;
  updated_at: string | null;
}

const _oauthConsentRowKeys: AssertRowKeys<OauthConsentRow, OauthConsents> = true;

/**
 * Per-(client, user) OAuth consent grants, Plan 3b Task 4, inventory §3
 * OA11/OA12. `oauth_consents` has a genuine composite unique index on
 * `(client_id, user_id)` (`Migration20200101012500_oauth_2.ts`:
 * `UNIQUE(client_id, user_id)`, mirrored on the entity as `uniques: [{
 * properties: ['client', 'user'] }]`), so OA12's upsert decision (task
 * brief ruling) is `em.upsert`, not a `nativeDelete` + `insert` pair — the
 * natural key IS unique, no fallback needed. Scope union-not-narrow (M5:
 * never narrow stored consent) stays in the SERVICE — this repository
 * writes exactly the scopes JSON it is given.
 */
export class OauthConsentsRepository extends TrekRepository<OauthConsents> {
  // ---------------------------------------------------------------------
  // OA11 — consent-sufficiency read
  // ---------------------------------------------------------------------

  /**
   * `SELECT scopes FROM oauth_consents WHERE client_id = ? AND user_id = ?`
   * `null` when no consent has been granted yet — the JSON parse of a
   * present-but-empty `scopes` value ("consent granted, zero scopes",
   * structurally distinct from "never consented") stays in the service,
   * unchanged.
   *
   * Named `findScopes`, not `find` — `EntityRepository#find` already exists
   * with an incompatible signature (`(where, options) => Promise<Entity[]>`);
   * shadowing it would either fail to compile or silently hide the base
   * method (same rule `upsertGrant` below follows for `#upsert`).
   */
  async findScopes(clientId: string, userId: number): Promise<{ scopes: string } | null> {
    const row = await this.findOne({ client: clientId, user: userId }, { fields: ['scopes'] });
    return row ? { scopes: row.scopes } : null;
  }

  // ---------------------------------------------------------------------
  // OA12 — consent grant (upsert)
  // ---------------------------------------------------------------------

  /**
   * `INSERT OR REPLACE INTO oauth_consents (client_id, user_id, scopes,
   *  updated_at) VALUES (?, ?, ?, CURRENT_TIMESTAMP)` —
   * **security-sensitive** (authorization grant). `em.upsert` with
   * `onConflictFields: ['client', 'user']` (the RELATION properties, not
   * their `persist(false)` mirrors — `Settings.repository.ts::upsertForUser`'s
   * precedent) against the entity's own `uniques: [{ properties: ['client',
   * 'user'] }]` — the natural key the migration's `UNIQUE(client_id,
   * user_id)` declares, verified against the migration before choosing this
   * over a delete+insert fallback (task brief ruling).
   *
   * `updated_at` is explicit in the payload, not left to the column's
   * `defaultRaw('CURRENT_TIMESTAMP')`: a default only fires on INSERT, and
   * `em.upsert`'s `'merge'` action updates ONLY the fields present in the
   * payload on a conflict (verified against the installed 7.2.1 behaviour
   * and the MikroORM docs: "values generated by property `onCreate` hooks…
   * are automatically excluded from the merge clause") — the legacy
   * statement's `INSERT OR REPLACE` always re-writes `updated_at` to
   * `CURRENT_TIMESTAMP` regardless of whether the row existed (SQLite's
   * `OR REPLACE` deletes-then-inserts, so there is no "update" branch to
   * distinguish), so this repository stamps it explicitly on every call
   * through `currentTimestamp(platform)`, matching that unconditional
   * behaviour rather than relying on a default that would only cover the
   * insert half.
   *
   * Named `upsertGrant`, not `upsert` — `EntityRepository#upsert` already
   * exists with an incompatible signature (`(entityOrData, options) =>
   * Promise<Entity>`); shadowing it would either fail to compile or silently
   * hide the base method, the same collision `Users.repository.ts::insertUser`
   * avoided with `create`.
   *
   * One more divergence from the legacy statement (Task 7 review, B-I1),
   * unobservable and strictly better: the legacy `INSERT OR REPLACE`
   * deletes-then-inserts, so a re-consent always assigned a NEW surrogate
   * `id`; `em.upsert` with `onConflictAction: 'merge'` keeps the existing
   * one. `oauth_consents` has only `id`/`client_id`/`user_id`/`scopes`/
   * `updated_at` and nothing reads `id`, so this is unobservable — and it
   * avoids the FK churn a delete+insert would otherwise cause if anything
   * ever did reference this row's surrogate key.
   */
  async upsertGrant(clientId: string, userId: number, scopes: string): Promise<void> {
    const platform = this.getEntityManager().getPlatform();
    await this.upsert(
      { client: clientId, user: userId, scopes, updated_at: currentTimestamp(platform) },
      { onConflictFields: ['client', 'user'], onConflictAction: 'merge' },
    );
  }
}
