{{- if and (not .Values.existingSecret) (not .Values.generateEncryptionKey) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "trek.fullname" . }}-secret
  labels:
    app: {{ include "trek.name" . }}
type: Opaque
data:
  {{ .Values.existingSecretKey | default "ENCRYPTION_KEY" }}: {{ .Values.secretEnv.ENCRYPTION_KEY | b64enc | quote }}
  {{- if .Values.secretEnv.ADMIN_EMAIL }}
  ADMIN_EMAIL: {{ .Values.secretEnv.ADMIN_EMAIL | b64enc | quote }}
  {{- end }}
  {{- if .Values.secretEnv.ADMIN_PASSWORD }}
  ADMIN_PASSWORD: {{ .Values.secretEnv.ADMIN_PASSWORD | b64enc | quote }}
  {{- end }}
  {{- if .Values.secretEnv.OIDC_CLIENT_SECRET }}
  OIDC_CLIENT_SECRET: {{ .Values.secretEnv.OIDC_CLIENT_SECRET | b64enc | quote }}
  {{- end }}
  {{- if .Values.secretEnv.UNSPLASH_ACCESS_KEY }}
  UNSPLASH_ACCESS_KEY: {{ .Values.secretEnv.UNSPLASH_ACCESS_KEY | b64enc | quote }}
  {{- end }}
  {{- if .Values.secretEnv.PLACES_API_KEY }}
  PLACES_API_KEY: {{ .Values.secretEnv.PLACES_API_KEY | b64enc | quote }}
  {{- end }}
  {{- if .Values.secretEnv.AMAP_API_KEY }}
  AMAP_API_KEY: {{ .Values.secretEnv.AMAP_API_KEY | b64enc | quote }}
  {{- end }}
  {{- if .Values.secretEnv.AMAP_API_SECRET }}
  AMAP_API_SECRET: {{ .Values.secretEnv.AMAP_API_SECRET | b64enc | quote }}
  {{- end }}
  {{- if .Values.secretEnv.VAPID_PRIVATE_KEY }}
  VAPID_PRIVATE_KEY: {{ .Values.secretEnv.VAPID_PRIVATE_KEY | b64enc | quote }}
  {{- end }}
  {{- if .Values.secretEnv.SMTP_PASS }}
  SMTP_PASS: {{ .Values.secretEnv.SMTP_PASS | b64enc | quote }}
  {{- end }}
  {{- if .Values.secretEnv.MAPBOX_ACCESS_TOKEN }}
  MAPBOX_ACCESS_TOKEN: {{ .Values.secretEnv.MAPBOX_ACCESS_TOKEN | b64enc | quote }}
  {{- end }}
  {{- if .Values.secretEnv.CARTO_API_KEY }}
  CARTO_API_KEY: {{ .Values.secretEnv.CARTO_API_KEY | b64enc | quote }}
  {{- end }}
  {{- if .Values.secretEnv.DEMO_ADMIN_PASS }}
  DEMO_ADMIN_PASS: {{ .Values.secretEnv.DEMO_ADMIN_PASS | b64enc | quote }}
  {{- end }}
{{- end }}

{{- if and (not .Values.existingSecret) (.Values.generateEncryptionKey) }}
{{- $secretName := printf "%s-secret" (include "trek.fullname" .) }}
{{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace $secretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    app: {{ include "trek.name" . }}
type: Opaque
stringData:
  {{- if and $existingSecret $existingSecret.data }}
  {{ .Values.existingSecretKey | default "ENCRYPTION_KEY" }}: {{ index $existingSecret.data (.Values.existingSecretKey | default "ENCRYPTION_KEY") | b64dec | quote }}
  {{- else }}
  {{ .Values.existingSecretKey | default "ENCRYPTION_KEY" }}: {{ randAlphaNum 32 | quote }}
  {{- end }}
  {{- if .Values.secretEnv.ADMIN_EMAIL }}
  ADMIN_EMAIL: {{ .Values.secretEnv.ADMIN_EMAIL | quote }}
  {{- end }}
  {{- if .Values.secretEnv.ADMIN_PASSWORD }}
  ADMIN_PASSWORD: {{ .Values.secretEnv.ADMIN_PASSWORD | quote }}
  {{- end }}
  {{- if .Values.secretEnv.OIDC_CLIENT_SECRET }}
  OIDC_CLIENT_SECRET: {{ .Values.secretEnv.OIDC_CLIENT_SECRET | quote }}
  {{- end }}
  {{- if .Values.secretEnv.UNSPLASH_ACCESS_KEY }}
  UNSPLASH_ACCESS_KEY: {{ .Values.secretEnv.UNSPLASH_ACCESS_KEY | quote }}
  {{- end }}
  {{- if .Values.secretEnv.PLACES_API_KEY }}
  PLACES_API_KEY: {{ .Values.secretEnv.PLACES_API_KEY | quote }}
  {{- end }}
  {{- if .Values.secretEnv.AMAP_API_KEY }}
  AMAP_API_KEY: {{ .Values.secretEnv.AMAP_API_KEY | quote }}
  {{- end }}
  {{- if .Values.secretEnv.AMAP_API_SECRET }}
  AMAP_API_SECRET: {{ .Values.secretEnv.AMAP_API_SECRET | quote }}
  {{- end }}
  {{- if .Values.secretEnv.VAPID_PRIVATE_KEY }}
  VAPID_PRIVATE_KEY: {{ .Values.secretEnv.VAPID_PRIVATE_KEY | quote }}
  {{- end }}
  {{- if .Values.secretEnv.SMTP_PASS }}
  SMTP_PASS: {{ .Values.secretEnv.SMTP_PASS | quote }}
  {{- end }}
  {{- if .Values.secretEnv.MAPBOX_ACCESS_TOKEN }}
  MAPBOX_ACCESS_TOKEN: {{ .Values.secretEnv.MAPBOX_ACCESS_TOKEN | quote }}
  {{- end }}
  {{- if .Values.secretEnv.CARTO_API_KEY }}
  CARTO_API_KEY: {{ .Values.secretEnv.CARTO_API_KEY | quote }}
  {{- end }}
  {{- if .Values.secretEnv.DEMO_ADMIN_PASS }}
  DEMO_ADMIN_PASS: {{ .Values.secretEnv.DEMO_ADMIN_PASS | quote }}
  {{- end }}
{{- end }}
