// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface AssignmentParticipantsTable {
  id: InsertOptional<number>;
  assignment_id: number;
  user_id: number;
}
