// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface AuditLogTable {
  id: InsertOptional<number>;
  created_at: InsertOptional<string | null>;
  user_id: InsertOptional<number | null>;
  action: string;
  resource: InsertOptional<string | null>;
  details: InsertOptional<string | null>;
  ip: InsertOptional<string | null>;
}
