// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface BucketListTable {
  id: InsertOptional<number>;
  user_id: number;
  name: string;
  lat: InsertOptional<number | null>;
  lng: InsertOptional<number | null>;
  country_code: InsertOptional<string | null>;
  notes: InsertOptional<string | null>;
  created_at: InsertOptional<string | null>;
  target_date: InsertOptional<string | null>;
  visited_at: InsertOptional<string | null>;
  visited_source: InsertOptional<string | null>;
  region_code: InsertOptional<string | null>;
}
