// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface BudgetItemsTable {
  id: InsertOptional<number>;
  trip_id: number;
  category: InsertOptional<string>;
  name: string;
  total_price: InsertOptional<number>;
  persons: InsertOptional<number | null>;
  days: InsertOptional<number | null>;
  note: InsertOptional<string | null>;
  sort_order: InsertOptional<number | null>;
  created_at: InsertOptional<string | null>;
  paid_by_user_id: InsertOptional<number | null>;
  expense_date: InsertOptional<string | null>;
  reservation_id: InsertOptional<number | null>;
  currency: InsertOptional<string | null>;
  exchange_rate: InsertOptional<number>;
  ticket_json: InsertOptional<string | null>;
  place_id: InsertOptional<number | null>;
}
