// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface BudgetSettlementsTable {
  id: InsertOptional<number>;
  trip_id: number;
  from_user_id: number;
  to_user_id: number;
  amount: InsertOptional<number>;
  created_at: InsertOptional<string | null>;
  created_by_user_id: InsertOptional<number | null>;
  currency: InsertOptional<string | null>;
  exchange_rate: InsertOptional<number>;
  settled_at: InsertOptional<string | null>;
  note: InsertOptional<string | null>;
}
