// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface BudgetItemPayersTable {
  id: InsertOptional<number>;
  budget_item_id: number;
  user_id: number;
  amount: InsertOptional<number>;
}
