// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface CategoriesTable {
  id: InsertOptional<number>;
  name: string;
  color: InsertOptional<string | null>;
  icon: InsertOptional<string | null>;
  user_id: InsertOptional<number | null>;
  created_at: InsertOptional<string | null>;
}
