// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface CollabPollVotesTable {
  id: InsertOptional<number>;
  poll_id: number;
  user_id: number;
  option_index: number;
  created_at: InsertOptional<string | null>;
}
