// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.

export interface CollectionPlaceLabelsTable {
  collection_place_id: number;
  label_id: number;
}
