// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface CollectionPlacesTable {
  id: InsertOptional<number>;
  collection_id: number;
  owner_id: number;
  saved_by: InsertOptional<number | null>;
  name: string;
  description: InsertOptional<string | null>;
  lat: InsertOptional<number | null>;
  lng: InsertOptional<number | null>;
  address: InsertOptional<string | null>;
  category_id: InsertOptional<number | null>;
  price: InsertOptional<number | null>;
  currency: InsertOptional<string | null>;
  notes: InsertOptional<string | null>;
  image_url: InsertOptional<string | null>;
  google_place_id: InsertOptional<string | null>;
  google_ftid: InsertOptional<string | null>;
  osm_id: InsertOptional<string | null>;
  website: InsertOptional<string | null>;
  phone: InsertOptional<string | null>;
  status: InsertOptional<string>;
  source_trip_id: InsertOptional<number | null>;
  source_place_id: InsertOptional<number | null>;
  links: InsertOptional<string | null>;
  sort_order: InsertOptional<number | null>;
  created_at: InsertOptional<string | null>;
  updated_at: InsertOptional<string | null>;
}
