// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface CollabMessagesTable {
  id: InsertOptional<number>;
  trip_id: number;
  user_id: number;
  text: string;
  reply_to: InsertOptional<number | null>;
  created_at: InsertOptional<string | null>;
  deleted: InsertOptional<number | null>;
}
