// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface CollabNotesTable {
  id: InsertOptional<number>;
  trip_id: number;
  user_id: number;
  category: InsertOptional<string | null>;
  title: string;
  content: InsertOptional<string | null>;
  color: InsertOptional<string | null>;
  pinned: InsertOptional<number | null>;
  created_at: InsertOptional<string | null>;
  updated_at: InsertOptional<string | null>;
  website: InsertOptional<string | null>;
}
