// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface CollabPollsTable {
  id: InsertOptional<number>;
  trip_id: number;
  user_id: number;
  question: string;
  options: string;
  multiple: InsertOptional<number | null>;
  closed: InsertOptional<number | null>;
  deadline: InsertOptional<string | null>;
  created_at: InsertOptional<string | null>;
}
