// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface CollectionsTable {
  id: InsertOptional<number>;
  owner_id: number;
  name: string;
  description: InsertOptional<string | null>;
  color: InsertOptional<string | null>;
  icon: InsertOptional<string | null>;
  cover_image: InsertOptional<string | null>;
  links: InsertOptional<string | null>;
  sort_order: InsertOptional<number | null>;
  created_at: InsertOptional<string | null>;
  updated_at: InsertOptional<string | null>;
}
