// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface CollabLinksTable {
  id: InsertOptional<number>;
  trip_id: number;
  user_id: number;
  title: string;
  url: string;
  pinned: InsertOptional<number | null>;
  created_at: InsertOptional<string | null>;
  updated_at: InsertOptional<string | null>;
}
