// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface CollectionPlaceRatingsTable {
  id: InsertOptional<number>;
  collection_place_id: number;
  user_id: number;
  rating: number;
  created_at: InsertOptional<string | null>;
}
