// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { ColumnType } from 'kysely';

/** A column an insert may leave out: the database assigns it (rowid, DEFAULT) or stores NULL. */
export type InsertOptional<T> = ColumnType<T, T | void, T>;
