// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface DawarichConnectionsTable {
  user_id: InsertOptional<number>;
  url: InsertOptional<string | null>;
  api_key: InsertOptional<string | null>;
  allow_insecure_tls: InsertOptional<number>;
  sync_enabled: InsertOptional<number>;
  last_sync_at: InsertOptional<string | null>;
  last_sync_state: InsertOptional<string>;
  last_sync_error: InsertOptional<string | null>;
  capabilities: InsertOptional<string | null>;
  created_at: InsertOptional<string | null>;
  updated_at: InsertOptional<string | null>;
}
