// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface DawarichVisitSuggestionsTable {
  id: InsertOptional<number>;
  user_id: number;
  source_visit_id: string;
  trip_id: InsertOptional<number | null>;
  name: string;
  lat: InsertOptional<number | null>;
  lng: InsertOptional<number | null>;
  started_at: string;
  ended_at: string;
  duration_minutes: InsertOptional<number>;
  local_date: string;
  source_status: InsertOptional<string>;
  confidence: InsertOptional<number | null>;
  confidence_band: InsertOptional<string | null>;
  country_code: InsertOptional<string | null>;
  state: InsertOptional<string>;
  target: InsertOptional<string | null>;
  accepted_place_id: InsertOptional<number | null>;
  accepted_journal_entry_id: InsertOptional<number | null>;
  accepted_bucket_list_item_id: InsertOptional<number | null>;
  matched_bucket_list_item_id: InsertOptional<number | null>;
  source_hash: string;
  accepted_hash: InsertOptional<string | null>;
  source_missing_at: InsertOptional<string | null>;
  first_seen_at: InsertOptional<string>;
  last_seen_at: InsertOptional<string>;
}
