// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface DayAssignmentsTable {
  id: InsertOptional<number>;
  day_id: number;
  place_id: number;
  order_index: InsertOptional<number | null>;
  notes: InsertOptional<string | null>;
  reservation_status: InsertOptional<string | null>;
  reservation_notes: InsertOptional<string | null>;
  reservation_datetime: InsertOptional<string | null>;
  created_at: InsertOptional<string | null>;
  assignment_time: InsertOptional<string | null>;
  assignment_end_time: InsertOptional<string | null>;
  leg_transport_mode: InsertOptional<string | null>;
  incoming_leg_transport_mode: InsertOptional<string | null>;
  end_day: InsertOptional<number>;
  accommodation_id: InsertOptional<number | null>;
  route_excluded: InsertOptional<number>;
}
