// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface DayAccommodationsTable {
  id: InsertOptional<number>;
  trip_id: number;
  place_id: InsertOptional<number | null>;
  start_day_id: number;
  end_day_id: number;
  check_in: InsertOptional<string | null>;
  check_in_end: InsertOptional<string | null>;
  check_out: InsertOptional<string | null>;
  confirmation: InsertOptional<string | null>;
  notes: InsertOptional<string | null>;
  created_at: InsertOptional<string | null>;
}
