// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface DayNotesTable {
  id: InsertOptional<number>;
  day_id: number;
  trip_id: number;
  text: string;
  time: InsertOptional<string | null>;
  icon: InsertOptional<string | null>;
  sort_order: InsertOptional<number | null>;
  created_at: InsertOptional<string | null>;
  color: InsertOptional<string | null>;
}
