// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface DaysTable {
  id: InsertOptional<number>;
  trip_id: number;
  day_number: number;
  date: InsertOptional<string | null>;
  notes: InsertOptional<string | null>;
  title: InsertOptional<string | null>;
  default_transport_mode: InsertOptional<string | null>;
}
