// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface DocumentProviderFieldsTable {
  id: InsertOptional<number>;
  provider_id: string;
  field_key: string;
  label: string;
  input_type: InsertOptional<string>;
  placeholder: InsertOptional<string | null>;
  hint: InsertOptional<string | null>;
  required: InsertOptional<number | null>;
  secret: InsertOptional<number | null>;
  sort_order: InsertOptional<number | null>;
}
