// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface DocumentSyncItemsTable {
  id: InsertOptional<number>;
  link_id: number;
  trip_id: number;
  file_id: InsertOptional<number | null>;
  trek_doc_uid: string;
  remote_id: InsertOptional<string | null>;
  remote_name: InsertOptional<string | null>;
  remote_version: InsertOptional<string | null>;
  remote_size: InsertOptional<number | null>;
  remote_modified_at: InsertOptional<string | null>;
  content_sha256: InsertOptional<string | null>;
  pushed_sha256: InsertOptional<string | null>;
  state: InsertOptional<string>;
  error_code: InsertOptional<string | null>;
  attempts: InsertOptional<number>;
  next_attempt_at: InsertOptional<string | null>;
  remote_missing_at: InsertOptional<string | null>;
  first_seen_at: InsertOptional<string>;
  last_seen_at: InsertOptional<string>;
  synced_at: InsertOptional<string | null>;
  remote_trashed_at: InsertOptional<string | null>;
}
