// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface DocumentConnectionsTable {
  id: InsertOptional<number>;
  trip_id: number;
  provider_id: string;
  owner_user_id: number;
  base_url: string;
  secrets: InsertOptional<string | null>;
  settings: InsertOptional<string>;
  allow_insecure_tls: InsertOptional<number>;
  capabilities: InsertOptional<string | null>;
  last_probe_at: InsertOptional<string | null>;
  last_probe_state: InsertOptional<string>;
  last_probe_error: InsertOptional<string | null>;
  created_at: InsertOptional<string | null>;
  updated_at: InsertOptional<string | null>;
}
