// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface FileLinksTable {
  id: InsertOptional<number>;
  file_id: number;
  reservation_id: InsertOptional<number | null>;
  assignment_id: InsertOptional<number | null>;
  place_id: InsertOptional<number | null>;
  created_at: InsertOptional<string | null>;
  budget_item_id: InsertOptional<number | null>;
}
