// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface GooglePlacePhotoMetaTable {
  place_id: string;
  attribution: InsertOptional<string | null>;
  fetched_at: number;
  error_at: InsertOptional<number | null>;
}
