// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface HiddenRegionsTable {
  id: InsertOptional<number>;
  user_id: number;
  region_code: string;
  country_code: string;
  created_at: InsertOptional<string | null>;
}
