// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface IdempotencyKeysTable {
  key: string;
  user_id: number;
  method: string;
  path: string;
  status_code: number;
  response_body: string;
  created_at: InsertOptional<number>;
}
