// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface InviteTokensTable {
  id: InsertOptional<number>;
  token: string;
  max_uses: InsertOptional<number>;
  used_count: InsertOptional<number>;
  expires_at: InsertOptional<string | null>;
  created_by: number;
  created_at: InsertOptional<string | null>;
  trip_id: InsertOptional<number | null>;
}
