// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface JourneyContributorsTable {
  journey_id: number;
  user_id: number;
  role: string;
  added_at: number;
  hide_skeletons: InsertOptional<number>;
}
