// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface JourneyShareTokensTable {
  id: InsertOptional<number>;
  journey_id: number;
  token: string;
  created_by: number;
  share_timeline: InsertOptional<number | null>;
  share_gallery: InsertOptional<number | null>;
  share_map: InsertOptional<number | null>;
  created_at: InsertOptional<string | null>;
  newest_first: InsertOptional<number>;
}
