// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface JourneyEntriesTable {
  id: InsertOptional<number>;
  journey_id: number;
  source_trip_id: InsertOptional<number | null>;
  source_place_id: InsertOptional<number | null>;
  author_id: number;
  type: string;
  title: InsertOptional<string | null>;
  story: InsertOptional<string | null>;
  entry_date: string;
  entry_time: InsertOptional<string | null>;
  location_name: InsertOptional<string | null>;
  location_lat: InsertOptional<number | null>;
  location_lng: InsertOptional<number | null>;
  mood: InsertOptional<string | null>;
  weather: InsertOptional<string | null>;
  tags: InsertOptional<string | null>;
  visibility: InsertOptional<string | null>;
  sort_order: InsertOptional<number | null>;
  created_at: number;
  updated_at: number;
  pros_cons: InsertOptional<string | null>;
  stats_excluded: InsertOptional<number>;
  dismissed: InsertOptional<number>;
  country_code: InsertOptional<string | null>;
  source_assignment_id: InsertOptional<number | null>;
  is_draft: InsertOptional<number>;
}
