// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface JourneyEntryPhotosTable {
  entry_id: number;
  journey_photo_id: number;
  sort_order: InsertOptional<number | null>;
  created_at: number;
}
