// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface JourneysTable {
  id: InsertOptional<number>;
  user_id: number;
  title: string;
  subtitle: InsertOptional<string | null>;
  cover_gradient: InsertOptional<string | null>;
  status: InsertOptional<string | null>;
  created_at: number;
  updated_at: number;
  cover_image: InsertOptional<string | null>;
  show_trip_tracks: InsertOptional<number>;
  show_verdict: InsertOptional<number>;
  show_mood: InsertOptional<number>;
  show_weather: InsertOptional<number>;
  status_override: InsertOptional<string | null>;
  photo_location: InsertOptional<number>;
}
