// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface JourneyBooksTable {
  id: InsertOptional<number>;
  journey_id: number;
  title: InsertOptional<string>;
  document: string;
  version: InsertOptional<number>;
  created_by: InsertOptional<number | null>;
  updated_by: InsertOptional<number | null>;
  created_at: InsertOptional<string | null>;
  updated_at: InsertOptional<string | null>;
}
