// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface JourneyPhotosTable {
  id: InsertOptional<number>;
  journey_id: number;
  photo_id: number;
  caption: InsertOptional<string | null>;
  shared: InsertOptional<number | null>;
  sort_order: InsertOptional<number | null>;
  provider: InsertOptional<string | null>;
  asset_id: InsertOptional<string | null>;
  owner_id: InsertOptional<number | null>;
  created_at: number;
}
