// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.

export interface JourneyTripsTable {
  journey_id: number;
  trip_id: number;
  added_at: number;
}
