// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface McpTokensTable {
  id: InsertOptional<number>;
  user_id: number;
  name: string;
  token_hash: string;
  token_prefix: string;
  created_at: InsertOptional<string | null>;
  last_used_at: InsertOptional<string | null>;
  kind: InsertOptional<string>;
  scope_mode: InsertOptional<string>;
  api_scopes: InsertOptional<string | null>;
}
