// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface NotificationsTable {
  id: InsertOptional<number>;
  type: string;
  scope: string;
  target: number;
  sender_id: InsertOptional<number | null>;
  recipient_id: number;
  title_key: string;
  title_params: InsertOptional<string | null>;
  text_key: string;
  text_params: InsertOptional<string | null>;
  positive_text_key: InsertOptional<string | null>;
  negative_text_key: InsertOptional<string | null>;
  positive_callback: InsertOptional<string | null>;
  negative_callback: InsertOptional<string | null>;
  response: InsertOptional<string | null>;
  navigate_text_key: InsertOptional<string | null>;
  navigate_target: InsertOptional<string | null>;
  is_read: InsertOptional<number | null>;
  created_at: InsertOptional<string | null>;
}
