// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface NotificationChannelPreferencesTable {
  user_id: number;
  event_type: string;
  channel: string;
  enabled: InsertOptional<number>;
}
