// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface OauthConsentsTable {
  id: InsertOptional<number>;
  client_id: string;
  user_id: number;
  scopes: InsertOptional<string>;
  updated_at: InsertOptional<string | null>;
}
