// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface OauthTokensTable {
  id: InsertOptional<number>;
  client_id: string;
  user_id: number;
  access_token_hash: string;
  refresh_token_hash: string;
  scopes: InsertOptional<string>;
  access_token_expires_at: string;
  refresh_token_expires_at: string;
  revoked_at: InsertOptional<string | null>;
  created_at: InsertOptional<string | null>;
  parent_token_id: InsertOptional<number | null>;
  audience: InsertOptional<string | null>;
}
