// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface OauthClientsTable {
  id: string;
  user_id: InsertOptional<number | null>;
  name: string;
  client_id: string;
  client_secret_hash: string;
  redirect_uris: InsertOptional<string>;
  allowed_scopes: InsertOptional<string>;
  created_at: InsertOptional<string | null>;
  is_public: InsertOptional<number>;
  created_via: InsertOptional<string>;
  allows_client_credentials: InsertOptional<number>;
}
