// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.

export interface PackingItemRecipientsTable {
  item_id: number;
  user_id: number;
}
