// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface PackingTemplateItemsTable {
  id: InsertOptional<number>;
  category_id: number;
  name: string;
  sort_order: InsertOptional<number>;
  weight_grams: InsertOptional<number | null>;
  quantity: InsertOptional<number>;
  bag_name: InsertOptional<string | null>;
}
