// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface PackingItemsTable {
  id: InsertOptional<number>;
  trip_id: number;
  name: string;
  checked: InsertOptional<number | null>;
  category: InsertOptional<string | null>;
  sort_order: InsertOptional<number | null>;
  created_at: InsertOptional<string | null>;
  weight_grams: InsertOptional<number | null>;
  bag_id: InsertOptional<number | null>;
  quantity: InsertOptional<number>;
  updated_at: InsertOptional<string | null>;
  is_private: InsertOptional<number>;
  owner_id: InsertOptional<number | null>;
  packed_quantity: InsertOptional<number | null>;
}
