// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface PackingTemplatesTable {
  id: InsertOptional<number>;
  name: string;
  created_by: number;
  created_at: InsertOptional<string | null>;
}
