// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface PackingBagsTable {
  id: InsertOptional<number>;
  trip_id: number;
  name: string;
  color: InsertOptional<string>;
  weight_limit_grams: InsertOptional<number | null>;
  sort_order: InsertOptional<number | null>;
  created_at: InsertOptional<string | null>;
  user_id: InsertOptional<number | null>;
}
