// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface PackingTemplateCategoriesTable {
  id: InsertOptional<number>;
  template_id: number;
  name: string;
  sort_order: InsertOptional<number>;
}
