// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface PasswordResetTokensTable {
  id: InsertOptional<number>;
  user_id: number;
  token_hash: string;
  expires_at: string;
  consumed_at: InsertOptional<string | null>;
  created_at: InsertOptional<string | null>;
  created_ip: InsertOptional<string | null>;
}
