// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface PhotosTable {
  id: InsertOptional<number>;
  trip_id: number;
  day_id: InsertOptional<number | null>;
  place_id: InsertOptional<number | null>;
  filename: string;
  original_name: string;
  file_size: InsertOptional<number | null>;
  mime_type: InsertOptional<string | null>;
  caption: InsertOptional<string | null>;
  taken_at: InsertOptional<string | null>;
  created_at: InsertOptional<string | null>;
}
