// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface PhotoProvidersTable {
  id: string;
  name: string;
  description: InsertOptional<string | null>;
  icon: InsertOptional<string | null>;
  enabled: InsertOptional<number | null>;
  sort_order: InsertOptional<number | null>;
}
