// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.

export interface PlaceTagsTable {
  place_id: number;
  tag_id: number;
}
