// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface PlaceShadowPicksTable {
  id: InsertOptional<number>;
  created_at: InsertOptional<string>;
  query: string;
  lang: InsertOptional<string | null>;
  bias_lat: InsertOptional<number | null>;
  bias_lng: InsertOptional<number | null>;
  source: string;
  live_rank: number;
  live_count: number;
  picked_name: string;
  picked_lat: number;
  picked_lng: number;
  picked_place_id: InsertOptional<string | null>;
}
