// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface PlaceDetailsCacheTable {
  place_id: string;
  lang: InsertOptional<string>;
  expanded: InsertOptional<number>;
  payload_json: string;
  fetched_at: number;
}
