// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface PlaceRegionsTable {
  place_id: InsertOptional<number>;
  country_code: string;
  region_code: string;
  region_name: string;
}
