// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface PlacesTable {
  id: InsertOptional<number>;
  trip_id: number;
  name: string;
  description: InsertOptional<string | null>;
  lat: InsertOptional<number | null>;
  lng: InsertOptional<number | null>;
  address: InsertOptional<string | null>;
  category_id: InsertOptional<number | null>;
  price: InsertOptional<number | null>;
  currency: InsertOptional<string | null>;
  reservation_status: InsertOptional<string | null>;
  reservation_notes: InsertOptional<string | null>;
  reservation_datetime: InsertOptional<string | null>;
  place_time: InsertOptional<string | null>;
  end_time: InsertOptional<string | null>;
  duration_minutes: InsertOptional<number | null>;
  notes: InsertOptional<string | null>;
  image_url: InsertOptional<string | null>;
  google_place_id: InsertOptional<string | null>;
  google_ftid: InsertOptional<string | null>;
  website: InsertOptional<string | null>;
  phone: InsertOptional<string | null>;
  transport_mode: InsertOptional<string | null>;
  created_at: InsertOptional<string | null>;
  updated_at: InsertOptional<string | null>;
  osm_id: InsertOptional<string | null>;
  route_geometry: InsertOptional<string | null>;
  route_color: InsertOptional<string | null>;
  stop_type: InsertOptional<string | null>;
  fill_percent: InsertOptional<number | null>;
  amap_poi_id: InsertOptional<string | null>;
  source: InsertOptional<string | null>;
  email: InsertOptional<string | null>;
  opening_hours: InsertOptional<string | null>;
}
