// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface PluginMetaMigrationsTable {
  plugin_id: string;
  migration_id: string;
  applied_at: InsertOptional<string | null>;
}
