// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface PluginOauthTokensTable {
  plugin_id: string;
  user_id: number;
  access_token: InsertOptional<string | null>;
  refresh_token: InsertOptional<string | null>;
  expires_at: InsertOptional<number | null>;
  scope: InsertOptional<string | null>;
  updated_at: InsertOptional<string>;
}
