// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface PluginsTable {
  id: string;
  name: string;
  description: InsertOptional<string | null>;
  type: InsertOptional<string>;
  icon: InsertOptional<string | null>;
  version: InsertOptional<string | null>;
  api_version: InsertOptional<number | null>;
  min_trek_version: InsertOptional<string | null>;
  permissions: InsertOptional<string | null>;
  granted_permissions: InsertOptional<string | null>;
  status: InsertOptional<string>;
  config: InsertOptional<string | null>;
  source_repo: InsertOptional<string | null>;
  source_commit: InsertOptional<string | null>;
  sha256: InsertOptional<string | null>;
  crash_count: InsertOptional<number>;
  last_error: InsertOptional<string | null>;
  reviewed_at: InsertOptional<string | null>;
  sort_order: InsertOptional<number>;
  installed_at: InsertOptional<string | null>;
  updated_at: InsertOptional<string | null>;
  enabled: InsertOptional<number>;
  capabilities: InsertOptional<string>;
  author_pubkey: InsertOptional<string | null>;
  dependencies: InsertOptional<string>;
  operator_egress: InsertOptional<number>;
  update_block_code: InsertOptional<string | null>;
  update_block_detail: InsertOptional<string | null>;
  update_block_version: InsertOptional<string | null>;
  trek_range: InsertOptional<string | null>;
  update_hold: InsertOptional<number>;
}
