// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface PluginActionsTable {
  plugin_id: string;
  action_key: string;
  label: string;
  hint: InsertOptional<string | null>;
  danger: InsertOptional<number>;
  sort_order: InsertOptional<number>;
  scope: InsertOptional<string>;
}
