// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.

export interface PluginOauthStateTable {
  state: string;
  plugin_id: string;
  user_id: number;
  verifier: string;
  created_at: number;
}
