// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface PluginUserErasureQueueTable {
  id: InsertOptional<number>;
  plugin_id: string;
  user_id: number;
  created_at: InsertOptional<string>;
}
