// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface PluginSettingsFieldsTable {
  id: InsertOptional<number>;
  plugin_id: string;
  field_key: string;
  label: InsertOptional<string | null>;
  input_type: InsertOptional<string>;
  placeholder: InsertOptional<string | null>;
  hint: InsertOptional<string | null>;
  required: InsertOptional<number>;
  secret: InsertOptional<number>;
  scope: InsertOptional<string>;
  options: InsertOptional<string | null>;
  oauth_config: InsertOptional<string | null>;
  sort_order: InsertOptional<number>;
  default_value: InsertOptional<string | null>;
}
