// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface PluginCapabilityAuditTable {
  id: InsertOptional<number>;
  plugin_id: string;
  acting_user_id: InsertOptional<number | null>;
  method: string;
  resource: InsertOptional<string | null>;
  code: string;
  ts: InsertOptional<string>;
  prev_hash: InsertOptional<string | null>;
  hash: string;
}
