// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface PluginErrorLogTable {
  id: InsertOptional<number>;
  plugin_id: string;
  ts: InsertOptional<string | null>;
  level: InsertOptional<string>;
  message: InsertOptional<string | null>;
  stack: InsertOptional<string | null>;
}
