// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface PluginEntityMetadataTable {
  id: InsertOptional<number>;
  plugin_id: string;
  entity_type: string;
  entity_id: number;
  key: string;
  value: InsertOptional<string | null>;
  updated_at: InsertOptional<string>;
}
