// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface PluginScheduledTasksTable {
  id: InsertOptional<number>;
  plugin_id: string;
  name: string;
  due_at: number;
  payload: InsertOptional<string>;
  every_ms: InsertOptional<number | null>;
  created_at: InsertOptional<string>;
}
