// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface PushSubscriptionsTable {
  id: InsertOptional<number>;
  user_id: number;
  endpoint: string;
  p256dh: string;
  auth: string;
  vapid_public_key: string;
  user_agent: InsertOptional<string | null>;
  created_at: InsertOptional<string>;
  last_success_at: InsertOptional<string | null>;
  failure_count: InsertOptional<number>;
}
