// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface ReservationsTable {
  id: InsertOptional<number>;
  trip_id: number;
  day_id: InsertOptional<number | null>;
  end_day_id: InsertOptional<number | null>;
  place_id: InsertOptional<number | null>;
  assignment_id: InsertOptional<number | null>;
  title: string;
  accommodation_id: InsertOptional<string | null>;
  reservation_time: InsertOptional<string | null>;
  reservation_end_time: InsertOptional<string | null>;
  location: InsertOptional<string | null>;
  confirmation_number: InsertOptional<string | null>;
  notes: InsertOptional<string | null>;
  status: InsertOptional<string | null>;
  type: InsertOptional<string | null>;
  created_at: InsertOptional<string | null>;
  metadata: InsertOptional<string | null>;
  day_plan_position: InsertOptional<number | null>;
  needs_review: InsertOptional<number>;
  external_source: InsertOptional<string | null>;
  external_id: InsertOptional<string | null>;
  external_owner_user_id: InsertOptional<number | null>;
  external_synced_at: InsertOptional<string | null>;
  sync_enabled: InsertOptional<number | null>;
  external_hash: InsertOptional<string | null>;
  url: InsertOptional<string | null>;
  ingest_state: InsertOptional<string>;
}
