// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface ReservationEndpointsTable {
  id: InsertOptional<number>;
  reservation_id: number;
  role: string;
  sequence: InsertOptional<number>;
  name: string;
  code: InsertOptional<string | null>;
  lat: number;
  lng: number;
  timezone: InsertOptional<string | null>;
  local_time: InsertOptional<string | null>;
  local_date: InsertOptional<string | null>;
  created_at: InsertOptional<string | null>;
}
