// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface RoadtripDayTracksTable {
  day_id: InsertOptional<number>;
  place_id: number;
  stray_km: InsertOptional<number | null>;
  created_at: InsertOptional<string | null>;
}
