// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface RoadtripViasTable {
  id: InsertOptional<number>;
  day_id: number;
  after_order_index: number;
  sequence: InsertOptional<number>;
  lat: number;
  lng: number;
  created_at: InsertOptional<string | null>;
}
