// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface RoadtripDayBoundariesTable {
  trip_id: number;
  day_number: number;
  from_assignment_id: number;
  to_assignment_id: InsertOptional<number | null>;
  fraction: number;
}
