// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface RouteUsageDailyTable {
  day: string;
  profile: string;
  surface: string;
  self_hosted: number;
  requests: InsertOptional<number>;
  waypoints: InsertOptional<number>;
  km: InsertOptional<number>;
  failed: InsertOptional<number>;
}
