// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface SchoolHolidayPeriodsTable {
  id: InsertOptional<number>;
  region_id: number;
  name: string;
  start_date: string;
  end_date: string;
}
