// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface ShareTokensTable {
  id: InsertOptional<number>;
  trip_id: number;
  token: string;
  created_by: number;
  share_map: InsertOptional<number | null>;
  share_bookings: InsertOptional<number | null>;
  share_packing: InsertOptional<number | null>;
  share_budget: InsertOptional<number | null>;
  share_collab: InsertOptional<number | null>;
  created_at: InsertOptional<string | null>;
  expires_at: InsertOptional<string | null>;
  share_travel_only: InsertOptional<number>;
  share_hide_images: InsertOptional<number>;
}
