// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface TagsTable {
  id: InsertOptional<number>;
  user_id: number;
  name: string;
  color: InsertOptional<string | null>;
  created_at: InsertOptional<string | null>;
}
