// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface TodoItemsTable {
  id: InsertOptional<number>;
  trip_id: number;
  name: string;
  checked: InsertOptional<number | null>;
  category: InsertOptional<string | null>;
  sort_order: InsertOptional<number | null>;
  due_date: InsertOptional<string | null>;
  description: InsertOptional<string | null>;
  assigned_user_id: InsertOptional<number | null>;
  priority: InsertOptional<number | null>;
  created_at: InsertOptional<string | null>;
  reminded_at: InsertOptional<string | null>;
}
