// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface TourTypesTable {
  key: string;
  label_key: string;
  icon: string;
  color: string;
  routing_profile: InsertOptional<string | null>;
  is_sport: InsertOptional<number>;
  enabled: InsertOptional<number>;
  sort_order: InsertOptional<number>;
}
