// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface TourWaypointsTable {
  id: InsertOptional<number>;
  place_id: number;
  lat: number;
  lng: number;
  role: string;
  sequence: number;
}
