// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.

import type { InsertOptional } from './columns';

export interface ToursTable {
  place_id: InsertOptional<number>;
  tour_type: string;
  distance: InsertOptional<number | null>;
  elevation_gain: InsertOptional<number | null>;
  elevation_loss: InsertOptional<number | null>;
  duration: InsertOptional<number | null>;
  difficulty: InsertOptional<string | null>;
  wanderer_ref: InsertOptional<string | null>;
  match_confidence: InsertOptional<number | null>;
  created_at: InsertOptional<string | null>;
  max_hiking_difficulty: InsertOptional<number>;
  planned_duration_minutes: InsertOptional<number | null>;
  break_additional_minutes: InsertOptional<number | null>;
}
