// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface TrekPhotosTable {
  id: InsertOptional<number>;
  provider: string;
  asset_id: InsertOptional<string | null>;
  owner_id: InsertOptional<number | null>;
  file_path: InsertOptional<string | null>;
  thumbnail_path: InsertOptional<string | null>;
  width: InsertOptional<number | null>;
  height: InsertOptional<number | null>;
  created_at: InsertOptional<string | null>;
  passphrase: InsertOptional<string | null>;
  media_type: InsertOptional<string>;
  duration_ms: InsertOptional<number | null>;
  taken_at: InsertOptional<string | null>;
  lat: InsertOptional<number | null>;
  lng: InsertOptional<number | null>;
}
