// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface TripAlbumLinksTable {
  id: InsertOptional<number>;
  trip_id: number;
  user_id: number;
  provider: string;
  album_id: string;
  album_name: InsertOptional<string>;
  sync_enabled: InsertOptional<number>;
  last_synced_at: InsertOptional<string | null>;
  created_at: InsertOptional<string | null>;
  passphrase: InsertOptional<string | null>;
}
