// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface TripMembersTable {
  id: InsertOptional<number>;
  trip_id: number;
  user_id: number;
  invited_by: InsertOptional<number | null>;
  added_at: InsertOptional<string | null>;
}
