// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface TripsTable {
  id: InsertOptional<number>;
  user_id: number;
  title: string;
  description: InsertOptional<string | null>;
  start_date: InsertOptional<string | null>;
  end_date: InsertOptional<string | null>;
  currency: InsertOptional<string | null>;
  cover_image: InsertOptional<string | null>;
  is_archived: InsertOptional<number | null>;
  reminder_days: InsertOptional<number | null>;
  feed_token: InsertOptional<string | null>;
  created_at: InsertOptional<string | null>;
  updated_at: InsertOptional<string | null>;
  reminder_sent_for: InsertOptional<string | null>;
}
