// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface TripDocumentLinksTable {
  id: InsertOptional<number>;
  trip_id: number;
  connection_id: number;
  provider_id: string;
  remote_scope_key: string;
  remote_root_id: InsertOptional<string | null>;
  remote_root_path: InsertOptional<string | null>;
  remote_label: InsertOptional<string>;
  direction: InsertOptional<string>;
  delete_policy: InsertOptional<string>;
  conflict_policy: InsertOptional<string>;
  sync_enabled: InsertOptional<number>;
  webhook_token: InsertOptional<string | null>;
  webhook_secret: InsertOptional<string | null>;
  webhook_subscription_id: InsertOptional<string | null>;
  remote_cursor: InsertOptional<string | null>;
  last_sync_at: InsertOptional<string | null>;
  last_sync_state: InsertOptional<string>;
  last_sync_error: InsertOptional<string | null>;
  failure_count: InsertOptional<number>;
  next_attempt_at: InsertOptional<string | null>;
  created_by: InsertOptional<number | null>;
  created_at: InsertOptional<string | null>;
  updated_at: InsertOptional<string | null>;
}
