// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface TripInviteTokensTable {
  id: InsertOptional<number>;
  trip_id: number;
  token: string;
  created_by: InsertOptional<number | null>;
  expires_at: InsertOptional<string | null>;
  created_at: InsertOptional<string | null>;
}
