// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface TripPhotosTable {
  id: InsertOptional<number>;
  trip_id: number;
  user_id: number;
  photo_id: number;
  shared: InsertOptional<number>;
  album_link_id: InsertOptional<number | null>;
  added_at: InsertOptional<string | null>;
}
