// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface TripFilesTable {
  id: InsertOptional<number>;
  trip_id: number;
  place_id: InsertOptional<number | null>;
  reservation_id: InsertOptional<number | null>;
  filename: string;
  original_name: string;
  file_size: InsertOptional<number | null>;
  mime_type: InsertOptional<string | null>;
  description: InsertOptional<string | null>;
  created_at: InsertOptional<string | null>;
  note_id: InsertOptional<number | null>;
  uploaded_by: InsertOptional<number | null>;
  starred: InsertOptional<number | null>;
  deleted_at: InsertOptional<string | null>;
  message_id: InsertOptional<number | null>;
}
