// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface UserSessionsTable {
  id: string;
  user_id: number;
  created_at: InsertOptional<string>;
  last_seen_at: InsertOptional<string>;
  expires_at: string;
  revoked_at: InsertOptional<string | null>;
  user_agent: InsertOptional<string | null>;
}
