// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface UserNoticeDismissalsTable {
  user_id: number;
  notice_id: string;
  dismissed_at: number;
  dismissed_app_version: InsertOptional<string | null>;
}
