// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface UsersTable {
  id: InsertOptional<number>;
  username: string;
  email: string;
  password_hash: string;
  role: InsertOptional<string>;
  maps_api_key: InsertOptional<string | null>;
  unsplash_api_key: InsertOptional<string | null>;
  amap_api_key: InsertOptional<string | null>;
  openweather_api_key: InsertOptional<string | null>;
  avatar: InsertOptional<string | null>;
  oidc_sub: InsertOptional<string | null>;
  oidc_issuer: InsertOptional<string | null>;
  last_login: InsertOptional<string | null>;
  mfa_enabled: InsertOptional<number | null>;
  mfa_secret: InsertOptional<string | null>;
  mfa_backup_codes: InsertOptional<string | null>;
  immich_url: InsertOptional<string | null>;
  immich_access_token: InsertOptional<string | null>;
  synology_url: InsertOptional<string | null>;
  synology_username: InsertOptional<string | null>;
  synology_password: InsertOptional<string | null>;
  synology_sid: InsertOptional<string | null>;
  must_change_password: InsertOptional<number | null>;
  password_version: InsertOptional<number>;
  feed_token: InsertOptional<string | null>;
  is_guest: InsertOptional<number>;
  created_at: InsertOptional<string | null>;
  updated_at: InsertOptional<string | null>;
  immich_api_key: InsertOptional<string | null>;
  synology_skip_ssl: InsertOptional<number>;
  synology_did: InsertOptional<string | null>;
  first_seen_version: InsertOptional<string>;
  login_count: InsertOptional<number>;
  immich_auto_upload: InsertOptional<number>;
  airtrail_url: InsertOptional<string | null>;
  airtrail_api_key: InsertOptional<string | null>;
  airtrail_allow_insecure_tls: InsertOptional<number | null>;
  airtrail_write_enabled: InsertOptional<number | null>;
  display_name: InsertOptional<string | null>;
  immich_allow_insecure_tls: InsertOptional<number>;
}
