// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface VacayUserYearsTable {
  id: InsertOptional<number>;
  user_id: number;
  plan_id: number;
  year: number;
  vacation_days: InsertOptional<number | null>;
  carried_over: InsertOptional<number | null>;
}
