// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface VacaySharesTable {
  id: InsertOptional<number>;
  owner_id: number;
  user_id: number;
  hidden: InsertOptional<number>;
  created_at: InsertOptional<string | null>;
}
