// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface VacayUserSettingsTable {
  user_id: InsertOptional<number>;
  year_type: InsertOptional<string>;
  year_start_month: InsertOptional<number>;
  year_start_day: InsertOptional<number>;
  hire_date: InsertOptional<string | null>;
}
