// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface VacayPlanMembersTable {
  id: InsertOptional<number>;
  plan_id: number;
  user_id: number;
  status: InsertOptional<string | null>;
  created_at: InsertOptional<string | null>;
}
