// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface VacayHolidayCalendarsTable {
  id: InsertOptional<number>;
  plan_id: number;
  type: InsertOptional<string>;
  region: string;
  label: InsertOptional<string | null>;
  color: InsertOptional<string>;
  sort_order: InsertOptional<number>;
}
