// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface VacayPlansTable {
  id: InsertOptional<number>;
  owner_id: number;
  block_weekends: InsertOptional<number | null>;
  holidays_enabled: InsertOptional<number | null>;
  holidays_region: InsertOptional<string | null>;
  school_holidays_enabled: InsertOptional<number | null>;
  company_holidays_enabled: InsertOptional<number | null>;
  carry_over_enabled: InsertOptional<number | null>;
  created_at: InsertOptional<string | null>;
  weekend_days: InsertOptional<string | null>;
  week_start: InsertOptional<number>;
}
