// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface VacayEntriesTable {
  id: InsertOptional<number>;
  plan_id: number;
  user_id: number;
  date: string;
  note: InsertOptional<string | null>;
  fraction: InsertOptional<number>;
  kind: InsertOptional<string>;
}
