// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface VacayUserColorsTable {
  id: InsertOptional<number>;
  user_id: number;
  plan_id: number;
  color: InsertOptional<string | null>;
}
