// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface WebauthnChallengesTable {
  id: InsertOptional<number>;
  challenge: string;
  user_id: InsertOptional<number | null>;
  type: string;
  expires_at: number;
  created_at: InsertOptional<string | null>;
}
