// Generated by scripts/generate-db-types.ts from the migrated schema. Do not edit by hand:
// change the migration, then run `npm run gen:db-types`.
import type { InsertOptional } from './columns';

export interface WebauthnCredentialsTable {
  id: InsertOptional<number>;
  user_id: number;
  credential_id: string;
  public_key: Buffer;
  counter: InsertOptional<number>;
  transports: InsertOptional<string | null>;
  device_type: InsertOptional<string | null>;
  backed_up: InsertOptional<number>;
  name: InsertOptional<string | null>;
  aaguid: InsertOptional<string | null>;
  created_at: InsertOptional<string | null>;
  last_used_at: InsertOptional<string | null>;
}
