import type { HelpContext, HelpGuide } from '../types'

/**
 * Help for the Atlas addon (`/atlas`): the world map of visited countries,
 * regions and the bucket list. The step actions that produce the pictures live
 * in `e2e/help/atlas.guide.ts`, keyed by the same ids.
 */

const ATLAS = 'Atlas'
const DAWARICH = 'Dawarich'

export const atlasGuides: HelpGuide[] = [
  {
    id: 'mark-country',
    context: 'atlas',
    icon: 'mapPin',
    size: 'guide',
    steps: 3,
    tips: 2,
    media: { steps: true, result: true },
    docs: { slug: ATLAS, anchor: 'marking-countries-as-visited' },
    related: ['unmark-country', 'regions', 'bucket-country'],
  },
  {
    id: 'unmark-country',
    context: 'atlas',
    icon: 'minusCircle',
    size: 'quick',
    steps: 2,
    tips: 1,
    media: { steps: true, result: false },
    docs: { slug: ATLAS, anchor: 'marking-countries-as-visited' },
    related: ['mark-country'],
  },
  {
    id: 'country-details',
    context: 'atlas',
    icon: 'search',
    size: 'quick',
    steps: 2,
    tips: 1,
    media: { steps: true, result: true },
    docs: { slug: ATLAS, anchor: 'statistics' },
    related: ['stats', 'planned-countries'],
  },
  {
    id: 'planned-countries',
    context: 'atlas',
    icon: 'eye',
    size: 'quick',
    steps: 2,
    tips: 2,
    media: { steps: true, result: true },
    docs: { slug: ATLAS, anchor: 'visited-and-planned-countries' },
    related: ['country-details', 'mark-country'],
  },
  {
    id: 'regions',
    context: 'atlas',
    icon: 'regions',
    size: 'guide',
    steps: 3,
    tips: 2,
    media: { steps: true, result: true },
    docs: { slug: ATLAS, anchor: 'sub-national-regions' },
    related: ['search-place', 'mark-country'],
  },
  {
    id: 'search-place',
    context: 'atlas',
    icon: 'landmark',
    size: 'guide',
    steps: 3,
    tips: 1,
    media: { steps: true, result: true },
    docs: { slug: ATLAS, anchor: 'marking-countries-as-visited' },
    related: ['regions', 'bucket-place'],
  },
  {
    id: 'bucket-country',
    context: 'atlas',
    icon: 'star',
    size: 'guide',
    steps: 3,
    tips: 2,
    media: { steps: true, result: true },
    docs: { slug: ATLAS, anchor: 'bucket-list' },
    related: ['bucket-place', 'mark-country'],
  },
  {
    id: 'bucket-place',
    context: 'atlas',
    icon: 'plus',
    size: 'guide',
    steps: 4,
    tips: 1,
    media: { steps: true, result: true },
    docs: { slug: ATLAS, anchor: 'bucket-list' },
    related: ['bucket-country'],
  },
  {
    id: 'stats',
    context: 'atlas',
    icon: 'chart',
    size: 'quick',
    steps: 2,
    tips: 2,
    media: { steps: true, result: false },
    docs: { slug: ATLAS, anchor: 'statistics' },
    related: ['country-details'],
  },
  {
    id: 'dawarich-countries',
    context: 'atlas',
    icon: 'globe',
    size: 'guide',
    steps: 3,
    tips: 2,
    media: { steps: true, result: true },
    docs: { slug: DAWARICH, anchor: 'countries' },
    related: ['mark-country', 'dawarich-wishes', 'stats'],
  },
  {
    id: 'dawarich-wishes',
    context: 'atlas',
    icon: 'checkCircle',
    size: 'guide',
    steps: 3,
    tips: 2,
    media: { steps: true, result: true },
    docs: { slug: DAWARICH, anchor: 'wishlist' },
    related: ['bucket-place', 'bucket-country', 'dawarich-countries'],
  },
]

export const atlasContext: HelpContext = {
  id: 'atlas',
  route: '/atlas',
  icon: 'globe',
  bullets: 6,
  guides: atlasGuides.map(g => g.id),
  docs: [{ slug: ATLAS }, { slug: DAWARICH }, { slug: 'Admin-Addons' }],
  hero: true,
}
