import type { HelpContext, HelpGuide } from '../types'

/**
 * Help for the desktop dashboard (`/dashboard`). The step actions that produce
 * the pictures for these guides live in `e2e/help/dashboard.guide.ts` and are
 * keyed by the same ids, so a step added here without an action there fails
 * the media run.
 */

const DOCS = {
  dashboard: { slug: 'My-Trips-Dashboard' },
  creating: { slug: 'Creating-a-Trip' },
  widgets: { slug: 'Dashboard-Widgets' },
  feeds: { slug: 'Calendar-Feeds' },
} as const

export const dashboardGuides: HelpGuide[] = [
  {
    id: 'create-trip',
    context: 'dashboard',
    icon: 'plus',
    size: 'guide',
    steps: 5,
    tips: 2,
    media: { steps: true, result: true },
    docs: DOCS.creating,
    related: ['cover-image', 'edit-trip'],
  },
  {
    id: 'edit-trip',
    context: 'dashboard',
    icon: 'pencil',
    size: 'quick',
    steps: 3,
    tips: 1,
    media: { steps: true, result: false },
    docs: { slug: 'Creating-a-Trip', anchor: 'fields' },
    related: ['cover-image', 'duplicate-trip'],
  },
  {
    id: 'cover-image',
    context: 'dashboard',
    icon: 'image',
    size: 'quick',
    steps: 3,
    tips: 1,
    media: { steps: true, result: true },
    docs: { slug: 'Creating-a-Trip', anchor: 'fields' },
    related: ['edit-trip'],
  },
  {
    id: 'duplicate-trip',
    context: 'dashboard',
    icon: 'copy',
    size: 'quick',
    steps: 2,
    tips: 1,
    media: { steps: true, result: true },
    docs: { slug: 'My-Trips-Dashboard', anchor: 'per-trip-actions' },
    related: ['create-trip'],
  },
  {
    id: 'archive-trip',
    context: 'dashboard',
    icon: 'archive',
    size: 'quick',
    steps: 3,
    tips: 0,
    media: { steps: true, result: false },
    docs: { slug: 'My-Trips-Dashboard', anchor: 'archived-trips' },
    related: ['delete-trip', 'filter-and-view'],
  },
  {
    id: 'delete-trip',
    context: 'dashboard',
    icon: 'trash',
    size: 'quick',
    steps: 2,
    tips: 0,
    media: { steps: true, result: false },
    docs: { slug: 'My-Trips-Dashboard', anchor: 'per-trip-actions' },
    related: ['archive-trip'],
  },
  {
    id: 'filter-and-view',
    context: 'dashboard',
    icon: 'filter',
    size: 'quick',
    steps: 2,
    tips: 0,
    media: { steps: true, result: true },
    docs: { slug: 'My-Trips-Dashboard', anchor: 'view-modes' },
    related: ['archive-trip'],
  },
  {
    id: 'calendar-feed',
    context: 'dashboard',
    icon: 'calendar',
    size: 'quick',
    steps: 3,
    tips: 1,
    media: { steps: true, result: false },
    docs: { slug: 'Calendar-Feeds', anchor: 'turning-a-feed-on' },
  },
  {
    id: 'widgets',
    context: 'dashboard',
    icon: 'layout',
    size: 'guide',
    steps: 4,
    tips: 0,
    media: { steps: true, result: true },
    docs: DOCS.widgets,
    link: '/settings?tab=appearance',
    related: ['currency-widget', 'timezones-widget'],
  },
  {
    id: 'currency-widget',
    context: 'dashboard',
    icon: 'coins',
    size: 'quick',
    steps: 2,
    tips: 1,
    media: { steps: true, result: false },
    docs: { slug: 'Dashboard-Widgets', anchor: 'currency-converter' },
    related: ['widgets'],
  },
  {
    id: 'timezones-widget',
    context: 'dashboard',
    icon: 'clock',
    size: 'quick',
    steps: 2,
    tips: 0,
    media: { steps: true, result: false },
    docs: { slug: 'Dashboard-Widgets', anchor: 'timezone-clock' },
    related: ['widgets'],
  },
]

export const dashboardContext: HelpContext = {
  id: 'dashboard',
  route: '/dashboard',
  icon: 'layout',
  bullets: 5,
  guides: dashboardGuides.map(g => g.id),
  docs: [DOCS.dashboard, DOCS.creating, DOCS.widgets, DOCS.feeds],
  hero: true,
}
