import type { HelpContext, HelpGuide } from '../types'

/**
 * Help for the Journey addon: the list of journeys (`/journey`) and one open
 * journal (`/journey/:id`) are two screens with their own guides. The step
 * actions that produce the pictures live in `e2e/help/journey.guide.ts`,
 * keyed by the same ids.
 */

const JOURNEY = 'Journey-Journal'

export const journeyGuides: HelpGuide[] = [
  {
    id: 'create-journey',
    context: 'journey',
    icon: 'plus',
    size: 'guide',
    steps: 3,
    tips: 2,
    media: { steps: true, result: true },
    docs: { slug: JOURNEY, anchor: 'creating-a-journey' },
    related: ['continue-writing', 'add-entry'],
  },
  {
    id: 'open-journey',
    context: 'journey',
    icon: 'bookOpen',
    size: 'quick',
    steps: 1,
    tips: 1,
    media: { steps: true, result: false },
    docs: { slug: JOURNEY, anchor: 'accessing-journey' },
    related: ['continue-writing'],
  },
  {
    id: 'continue-writing',
    context: 'journey',
    icon: 'pencil',
    size: 'quick',
    steps: 1,
    tips: 1,
    media: { steps: true, result: false },
    docs: { slug: JOURNEY, anchor: 'getting-around-a-long-journal' },
    related: ['add-entry', 'open-journey'],
  },
]

export const journeyContext: HelpContext = {
  id: 'journey',
  route: '/journey',
  icon: 'bookOpen',
  bullets: 3,
  guides: journeyGuides.map(g => g.id),
  docs: [{ slug: JOURNEY }, { slug: 'Admin-Addons' }],
  hero: true,
}

export const journalGuides: HelpGuide[] = [
  {
    id: 'add-entry',
    context: 'journey-detail',
    icon: 'plus',
    size: 'guide',
    steps: 4,
    tips: 2,
    media: { steps: true, result: true },
    docs: { slug: JOURNEY, anchor: 'journal-entries' },
    related: ['entry-photos', 'pros-cons', 'suggestions'],
  },
  {
    id: 'entry-photos',
    context: 'journey-detail',
    icon: 'image',
    size: 'guide',
    steps: 3,
    tips: 2,
    media: { steps: true, result: true },
    docs: { slug: JOURNEY, anchor: 'journal-entries' },
    related: ['add-entry', 'gallery-map'],
  },
  {
    id: 'suggestions',
    context: 'journey-detail',
    icon: 'sparkles',
    size: 'guide',
    steps: 3,
    tips: 2,
    media: { steps: true, result: true },
    docs: { slug: JOURNEY, anchor: 'creating-a-journey' },
    related: ['add-entry', 'link-trip'],
  },
  {
    id: 'add-on-day',
    context: 'journey-detail',
    icon: 'calendar',
    size: 'quick',
    steps: 2,
    tips: 1,
    media: { steps: true, result: false },
    docs: { slug: JOURNEY, anchor: 'getting-around-a-long-journal' },
    related: ['add-entry'],
  },
  {
    id: 'pros-cons',
    context: 'journey-detail',
    icon: 'thumbsUp',
    size: 'quick',
    steps: 2,
    tips: 1,
    media: { steps: true, result: true },
    docs: { slug: JOURNEY, anchor: 'journal-entries' },
    related: ['entry-fields', 'add-entry'],
  },
  {
    id: 'search-journey',
    context: 'journey-detail',
    icon: 'search',
    size: 'quick',
    steps: 2,
    tips: 2,
    media: { steps: true, result: false },
    docs: { slug: JOURNEY, anchor: 'getting-around-a-long-journal' },
    related: ['gallery-map'],
  },
  {
    id: 'gallery-map',
    context: 'journey-detail',
    icon: 'gallery',
    size: 'quick',
    steps: 2,
    tips: 2,
    media: { steps: true, result: false },
    docs: { slug: JOURNEY, anchor: 'map-view' },
    related: ['entry-photos', 'share-public'],
  },
  {
    id: 'entry-fields',
    context: 'journey-detail',
    icon: 'filter',
    size: 'quick',
    steps: 2,
    tips: 1,
    media: { steps: true, result: false },
    docs: { slug: JOURNEY, anchor: 'entry-fields' },
    related: ['pros-cons'],
  },
  {
    id: 'link-trip',
    context: 'journey-detail',
    icon: 'link',
    size: 'guide',
    steps: 3,
    tips: 2,
    media: { steps: true, result: true },
    docs: { slug: JOURNEY, anchor: 'creating-a-journey' },
    related: ['suggestions'],
  },
  {
    id: 'share-public',
    context: 'journey-detail',
    icon: 'share',
    size: 'guide',
    steps: 3,
    tips: 2,
    media: { steps: true, result: false },
    docs: { slug: JOURNEY, anchor: 'public-sharing' },
    related: ['contributors', 'gallery-map'],
  },
  {
    id: 'contributors',
    context: 'journey-detail',
    icon: 'userPlus',
    size: 'guide',
    steps: 3,
    tips: 1,
    media: { steps: true, result: false },
    docs: { slug: JOURNEY, anchor: 'creating-a-journey' },
    related: ['share-public'],
  },
  {
    id: 'studio',
    context: 'journey-detail',
    icon: 'book',
    size: 'quick',
    steps: 2,
    tips: 2,
    media: { steps: true, result: true },
    docs: { slug: JOURNEY, anchor: 'trek-studio' },
    related: ['entry-photos'],
  },
  {
    id: 'archive-journey',
    context: 'journey-detail',
    icon: 'archive',
    size: 'quick',
    steps: 2,
    tips: 2,
    media: { steps: true, result: false },
    docs: { slug: JOURNEY, anchor: 'creating-a-journey' },
    related: ['link-trip'],
  },
]

export const journalContext: HelpContext = {
  id: 'journey-detail',
  parent: 'journey',
  icon: 'bookOpen',
  bullets: 6,
  guides: journalGuides.map(g => g.id),
  docs: [{ slug: JOURNEY }, { slug: 'Public-Share-Links' }],
  hero: true,
}

/** TREK Studio, the photo-book designer that opens over a journal (`/journey/:id/studio`). */
export const studioGuides: HelpGuide[] = [
  {
    id: 'studio-auto-layout',
    context: 'journey-studio',
    icon: 'sparkles',
    size: 'guide',
    steps: 3,
    tips: 2,
    media: { steps: true, result: true },
    docs: { slug: JOURNEY, anchor: 'trek-studio' },
    related: ['studio-pages', 'studio-layouts'],
  },
  {
    id: 'studio-pages',
    context: 'journey-studio',
    icon: 'book',
    size: 'guide',
    steps: 3,
    tips: 2,
    media: { steps: true, result: true },
    docs: { slug: JOURNEY, anchor: 'trek-studio' },
    related: ['studio-layouts', 'studio-spread-file'],
  },
  {
    id: 'studio-layouts',
    context: 'journey-studio',
    icon: 'layout',
    size: 'quick',
    steps: 2,
    tips: 1,
    media: { steps: true, result: true },
    docs: { slug: JOURNEY, anchor: 'trek-studio' },
    related: ['studio-auto-layout', 'studio-content'],
  },
  {
    id: 'studio-content',
    context: 'journey-studio',
    icon: 'image',
    size: 'guide',
    steps: 3,
    tips: 2,
    media: { steps: true, result: true },
    docs: { slug: JOURNEY, anchor: 'trek-studio' },
    related: ['studio-properties', 'studio-elements'],
  },
  {
    id: 'studio-elements',
    context: 'journey-studio',
    icon: 'plus',
    size: 'quick',
    steps: 2,
    tips: 1,
    media: { steps: true, result: false },
    docs: { slug: JOURNEY, anchor: 'trek-studio' },
    related: ['studio-travel', 'studio-properties'],
  },
  {
    id: 'studio-travel',
    context: 'journey-studio',
    icon: 'globe',
    size: 'quick',
    steps: 2,
    tips: 1,
    media: { steps: true, result: false },
    docs: { slug: JOURNEY, anchor: 'trek-studio' },
    related: ['studio-elements'],
  },
  {
    id: 'studio-properties',
    context: 'journey-studio',
    icon: 'panelRight',
    size: 'guide',
    steps: 3,
    tips: 2,
    media: { steps: true, result: false },
    docs: { slug: JOURNEY, anchor: 'trek-studio' },
    related: ['studio-content', 'studio-layouts'],
  },
  {
    id: 'studio-format',
    context: 'journey-studio',
    icon: 'filter',
    size: 'quick',
    steps: 2,
    tips: 2,
    media: { steps: true, result: false },
    docs: { slug: JOURNEY, anchor: 'trek-studio' },
    related: ['studio-export'],
  },
  {
    id: 'studio-export',
    context: 'journey-studio',
    icon: 'upload',
    size: 'guide',
    steps: 3,
    tips: 2,
    media: { steps: true, result: false },
    docs: { slug: JOURNEY, anchor: 'trek-studio' },
    related: ['studio-format', 'studio-spread-file'],
  },
  {
    id: 'studio-spread-file',
    context: 'journey-studio',
    icon: 'fileInput',
    size: 'quick',
    steps: 2,
    tips: 1,
    media: { steps: true, result: false },
    docs: { slug: JOURNEY, anchor: 'trek-studio' },
    related: ['studio-export', 'studio-pages'],
  },
]

export const studioContext: HelpContext = {
  id: 'journey-studio',
  parent: 'journey',
  icon: 'book',
  bullets: 6,
  guides: studioGuides.map(g => g.id),
  docs: [{ slug: JOURNEY, anchor: 'trek-studio' }],
  hero: true,
}
