import type { HelpContext, HelpGuide } from '../types'

/**
 * Help for the Vacay addon (`/vacay`): the personal leave planner. The step
 * actions that produce the pictures live in `e2e/help/vacay.guide.ts`, keyed
 * by the same ids.
 */

const VACAY = 'Vacay'

export const vacayGuides: HelpGuide[] = [
  {
    id: 'log-day',
    context: 'vacay',
    icon: 'calendarCheck',
    size: 'guide',
    steps: 3,
    tips: 2,
    media: { steps: true, result: true },
    docs: { slug: VACAY, anchor: 'calendar-view' },
    related: ['half-day', 'comp-day', 'entitlement'],
  },
  {
    id: 'half-day',
    context: 'vacay',
    icon: 'halfDay',
    size: 'quick',
    steps: 3,
    tips: 1,
    media: { steps: true, result: true },
    docs: { slug: VACAY, anchor: 'half-days-and-comp-days' },
    related: ['log-day', 'comp-day'],
  },
  {
    id: 'comp-day',
    context: 'vacay',
    icon: 'hourglass',
    size: 'quick',
    steps: 2,
    tips: 1,
    media: { steps: true, result: true },
    docs: { slug: VACAY, anchor: 'half-days-and-comp-days' },
    related: ['log-day', 'half-day'],
  },
  {
    id: 'entitlement',
    context: 'vacay',
    icon: 'calculator',
    size: 'quick',
    steps: 2,
    tips: 1,
    media: { steps: true, result: true },
    docs: { slug: VACAY, anchor: 'year-plans' },
    related: ['carry-over', 'years'],
  },
  {
    id: 'years',
    context: 'vacay',
    icon: 'calendarRange',
    size: 'quick',
    steps: 3,
    tips: 0,
    media: { steps: true, result: true },
    docs: { slug: VACAY, anchor: 'year-plans' },
    related: ['entitlement', 'leave-year'],
  },
  {
    id: 'company-holidays',
    context: 'vacay',
    icon: 'building',
    size: 'guide',
    steps: 3,
    tips: 1,
    media: { steps: true, result: true },
    docs: { slug: VACAY, anchor: 'calendar-view' },
    related: ['public-holidays', 'log-day'],
  },
  {
    id: 'public-holidays',
    context: 'vacay',
    icon: 'flag',
    size: 'guide',
    steps: 3,
    tips: 1,
    media: { steps: true, result: true },
    docs: { slug: VACAY, anchor: 'calendar-view' },
    related: ['school-holidays', 'company-holidays'],
  },
  {
    id: 'school-holidays',
    context: 'vacay',
    icon: 'graduationCap',
    size: 'guide',
    steps: 3,
    tips: 1,
    media: { steps: true, result: true },
    docs: { slug: VACAY, anchor: 'manually-maintained-school-holidays' },
    // The catalogue those holidays come from is kept under Admin.
    related: ['public-holidays', 'school-holiday-catalog'],
  },
  {
    id: 'weekends',
    context: 'vacay',
    icon: 'calendarOff',
    size: 'quick',
    steps: 3,
    tips: 0,
    media: { steps: true, result: false },
    docs: { slug: VACAY, anchor: 'calendar-view' },
    related: ['leave-year'],
  },
  {
    id: 'leave-year',
    context: 'vacay',
    icon: 'calendarDays',
    size: 'quick',
    steps: 2,
    tips: 1,
    media: { steps: true, result: false },
    docs: { slug: VACAY, anchor: 'leave-year' },
    related: ['years', 'carry-over'],
  },
  {
    id: 'carry-over',
    context: 'vacay',
    icon: 'repeat',
    size: 'quick',
    steps: 2,
    tips: 1,
    media: { steps: true, result: false },
    docs: { slug: VACAY, anchor: 'year-plans' },
    related: ['entitlement'],
  },
  {
    id: 'invite',
    context: 'vacay',
    icon: 'userPlus',
    size: 'guide',
    steps: 3,
    tips: 2,
    media: { steps: true, result: true },
    docs: { slug: VACAY, anchor: 'inviting-collaborators' },
    related: ['share-calendar'],
  },
  {
    id: 'share-calendar',
    context: 'vacay',
    icon: 'share',
    size: 'guide',
    steps: 3,
    tips: 2,
    media: { steps: true, result: true },
    docs: { slug: VACAY, anchor: 'sharing-your-calendar-view-only' },
    related: ['invite'],
  },
]

export const vacayContext: HelpContext = {
  id: 'vacay',
  route: '/vacay',
  icon: 'calendarDays',
  bullets: 5,
  guides: vacayGuides.map(g => g.id),
  docs: [{ slug: VACAY }, { slug: 'Admin-Addons' }],
  hero: true,
}
