worker_processes auto;

events { worker_connections 1024; }

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    client_max_body_size 500M;
    sendfile on;

    proxy_connect_timeout  10s;
    proxy_read_timeout     300s;
    proxy_send_timeout     120s;

    upstream trek { server trek_app:3000; }

    # HTTP → redirige a HTTPS return 301 https://$host:446$request_uri; 
    server {
        listen 80;
        server_name localhost rodadas.info www.rodadas.info trekwanderer.info www.trekwanderer.info;
        
        return 301 https://$host$request_uri;   # ← correcto
    }

    # HTTPS
        server {listen 443 ssl;
        http2 on;
        server_name rodadas.info www.rodadas.info trekwanderer.info www.trekwanderer.info localhost;
        client_max_body_size 500M;

        ssl_certificate     /certs/fullchain.pem;
        ssl_certificate_key /certs/privkey.pem;
        ssl_protocols       TLSv1.2 TLSv1.3;
        ssl_ciphers         HIGH:!aNULL:!MD5;

        # Trek es una app monolítica — todo va al mismo contenedor
        location /mcp {
            proxy_pass http://trek;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
    	    proxy_set_header X-Real-IP $remote_addr;
    	    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    	    proxy_set_header X-Forwarded-Proto https;
    	    proxy_set_header Connection '';
    	    proxy_buffering off;
    	    proxy_cache off;
    	    proxy_read_timeout 86400s;
     	     chunked_transfer_encoding on;
	}
        location / {
            proxy_pass http://trek;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
            proxy_cache_bypass $http_upgrade;
            proxy_read_timeout 300s;
        }
    }
}
